apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telegraf.fullname" . }}
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
data:
{{- if .Values.override_config.toml }}
  telegraf.conf: |+
    {{- .Values.override_config.toml | nindent 4 }}
{{- else }}
  telegraf.conf: |+
    {{ template "global_tags" .Values.config.global_tags }}
    {{ template "agent" .Values.config.agent }}
    {{ template "processors" .Values.config.processors }}
    {{ template "aggregators" .Values.config.aggregators }}
    {{ template "outputs" .Values.config.outputs }}
    {{ template "monitor_self" .Values.config.monitor_self }}

    {{- if not (has "diskio" .Values.disabledInputs) }}
    [[inputs.diskio]]
    {{- .Values.config.inputs.diskio | nindent 4 }}
    {{- end }}

    {{- if not (has "kernel" .Values.disabledInputs) }}
    [[inputs.kernel]]
    {{- .Values.config.inputs.kernel | nindent 4 }}
    {{- end }}

    {{- if not (has "mem" .Values.disabledInputs) }}
    [[inputs.mem]]
    {{- .Values.config.inputs.mem | nindent 4 }}
    {{- end }}

    {{- if not (has "net" .Values.disabledInputs) }}
    [[inputs.net]]
    {{- .Values.config.inputs.net | nindent 4 }}
    {{- end }}

    {{- if not (has "processes" .Values.disabledInputs) }}
    [[inputs.processes]]
    {{- .Values.config.inputs.processes | nindent 4 }}
    {{- end }}

    {{- if not (has "swap" .Values.disabledInputs) }}
    [[inputs.swap]]
    {{- .Values.config.inputs.swap | nindent 4 }}
    {{- end }}

    {{- if not (has "system" .Values.disabledInputs) }}
    [[inputs.system]]
    {{- .Values.config.inputs.system | nindent 4 }}
    {{- end }}

    {{- if not (has "cpu" .Values.disabledInputs) }}
    [[inputs.cpu]]
    percpu = true
    totalcpu = true
    collect_cpu_time = false
    report_active = false
    {{- .Values.config.inputs.cpu | nindent 4 }}
    {{- end }}

    {{- if not (has "disk" .Values.disabledInputs) }}
    [[inputs.disk]]
    ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
    {{ .Values.config.inputs.disk | nindent 4 }}
    {{- end }}

    {{- if not (has "docker" .Values.disabledInputs) }}
    [[inputs.docker]]
    endpoint = "unix:///var/run/docker.sock"
    {{ .Values.config.inputs.docker | nindent 4 }}
    {{- end }}

    {{- if not (has "kubernetes" .Values.disabledInputs) }}
    [[inputs.kubernetes]]
    url = "https://$HOSTIP:10250"
    bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
    insecure_skip_verify = true
    {{ .Values.config.inputs.kubernetes | nindent 4 }}
    {{- end }}
{{- end }}
